Cover DirectoryHelpers with unit tests #16
Teodor92/MoreDotNet pull request #23
Opened 2016-10-11 09:10 UTC by leonpw

2016-10-11 17:33 UTC, Teodor92 requested changes
Looks good - if could do the minor style changes, I'll merge it in :)

P.S. Sorry about the missing contribution/code style guidelines - will add them as soon as possible.

2016-10-11 17:33 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Collections/EnumerableExtensions/EmptyIfNullTests.cs
> +        public void EmtyIfNull_ShouldReturnEqualCollection()
There's a typo here

2016-10-11 17:33 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Collections/EnumerableExtensions/EmptyIfNullTests.cs
> +        {
Use the following naming convention for tests:
[MethodName]_[TestSetup]_Should[ExpectedResult]
So basically:
EmtyIfNull_ShouldReturnEqualCollection
can be written as:
 EmtyIfNull_WhenGivenNonNullEnumerable_ShouldReturnEqualCollection

2016-10-11 17:33 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Collections/EnumerableExtensions/ForEachTests.cs
> +                () => EnumerableExtensions.ForEach<int>(null, null));
When asserting for exceptions, please use the generic overload:
Assert.Throws<T>
Example:
Assert.Throws(typeof(ArgumentNullException), () => EnumerableExtensions.ForEach<int>(null, null));
can be written as:
Assert.Throws<ArgumentNullException>(() => EnumerableExtensions.ForEach<int>(null, null));

2016-10-12 08:22 UTC, leonpw commented
Okay, I fixed it. Thanks for your comments!

2016-10-13 19:19 UTC, merged