Added XmlExtensions Unit Tests.
Teodor92/MoreDotNet pull request #24
Opened 2016-10-13 19:58 UTC by michelvosje

Implemented the XmlExtensionsUnitTests class for ticket #14.

2016-10-13 20:39 UTC, Teodor92 requested changes
Have in mind that there are a few test cases missing. For example:
- What happens if you try to deserialize to an incorrect type?

Anyway if you fix the few remarks I made in the comments, I will merge the PR :)

2016-10-13 20:39 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/XmlExtensions/XmlExtensionsTests.cs
> +            Assert.NotNull(testObject.XmlSerialize());
This just checks if the returned string is not null, but is it truly correctly serialized? An additional check will make the test better.

2016-10-13 20:39 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/XmlExtensions/XmlExtensionsTests.cs
> +            Assert.NotNull(testSerializedObject.XmlDeserialize<object>());
Same as above - it necessary to check if the deserialization is correct.

2016-10-13 20:39 UTC, Teodor92 commented on Source/MoreDotNet.Test/MoreDotNet.Tests.csproj
> +    </Reference>
Please remove the reference to Microsoft.VisualStudio.QualityTools.UnitTestFramework.

2016-10-13 20:57 UTC, michelvosje commented
Yes you are right. Got a little bit short on time. Will fix it tomorrow.

2016-10-16 19:19 UTC, michelvosje commented
I fixed the issues. What now?

2016-10-18 16:58 UTC, Teodor92 approved these changes

2016-10-18 16:58 UTC, merged

2016-10-18 16:59 UTC, Teodor92 commented
Merged!

2016-10-18 18:45 UTC, michelvosje commented
Doing even small tickets like these give me more experience with git, Github and how to contribute to open projects.
Ty.