Added ObjectExtensions tests
Teodor92/MoreDotNet pull request #27
Opened 2016-10-15 21:40 UTC by goggenb

Added test cases for ObjectExtensions

2016-10-18 17:13 UTC, Teodor92 requested changes
Looks good, just a few organizational tweaks needed. Well merge after this :)

2016-10-18 17:13 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/ObjectExtensions/TypeCastTests.cs
> +    public class TypeCastTests
Please rename the test class to AsTests to reflect the method tested.

2016-10-18 17:13 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/ObjectExtensions/TypeCastTests.cs
> +        public void ToDictionary_Null_ShouldThrowArgumentNullException()
Please move all Test related to ToDictionary to separate class.

2016-10-18 17:13 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/ObjectExtensions/TypeCheckTests.cs
> +    public class TypeCheckTests
Please rename the test class to IsTests to reflect the method tested.

2016-10-18 17:13 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/ObjectExtensions/TypeCheckTests.cs
> +        public void IsNot_NullItem_ShouldThrowShouldThrowArgumentNullException()
Please move the IsNot tests to a separate class.

2016-10-18 17:13 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/ObjectExtensions/TypeCheckTests.cs
> +        {
Please rename to IsNot_BIsNotA_ShouldReturnTrue to reflect the method tested.

2016-10-18 17:13 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/ObjectExtensions/TypeCheckTests.cs
> +        {
Same as above.

2016-10-19 11:53 UTC, goggenb commented
Hope i fixed everything with this commit :)

2016-10-19 19:53 UTC, Teodor92 approved these changes

2016-10-19 19:53 UTC, merged

2016-10-19 19:53 UTC, Teodor92 commented
Merged! Thanks!