Added tests for RandomExtensions  #12
Teodor92/MoreDotNet pull request #35
Opened 2016-10-26 20:40 UTC by georgimanov

2016-10-27 10:43 UTC, Teodor92 requested changes

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextBoolTests.cs
> +                int currentCounter = 0;
What is this for? You initialize it and increment it, but never use it?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextBoolTests.cs
> +                var nextBools = new bool[currentCount];
This is not used anywhere?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextBoolTests.cs
> +                    if (random.NextBool(0.5))
No need to specify 0.5 explicitly - it's the default value.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextBoolTests.cs
> +    public class NextBoolTests
Missing test case: What happens if the random is null?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            Assert.IsType<char>(result);
This check is a but pointless? Can you think of a scenario where the NextChar() method wont return a Char? The return type is guaranteed by the method signature.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            randomMock.Setup(r => r.Next(It.IsAny<int>(), It.IsAny<int>())).Returns((int)mockedResult);
`(int)mockedResult` - you don't need the explicit cast here.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            Assert.Equal((int)mockedResult, (int)result);
`(int)mockedResult, (int)result` - no need for the casts

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            randomMock.Setup(r => r.Next(It.IsAny<int>(), It.IsAny<int>())).Returns((int)mockedResult);
Please remove redundant cast.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            Assert.Equal((int)mockedResult, (int)result);
Please remove redundant cast.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            Assert.Equal((int)mockedResult, (int)result);
Please remove redundant cast.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            randomMock.Setup(r => r.Next(It.IsAny<int>(), It.IsAny<int>())).Returns((int)mockedResult);
Please remove redundant cast.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            randomMock.Setup(r => r.Next(It.IsAny<int>(), It.IsAny<int>())).Returns((int)mockedResult);
Ok, I think you get the idea - please remove redundant casts in every test.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +            char result = randomMock.Object.NextChar(MoreDotNet.Models.CharType.AlphabeticLower);
Please use a using statement for this:
using MoreDotNet.Models;

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +        public void NextChar_ShoudReturnChar_CapitalLetter()
1. Please use the following naming convention -> [MethodName]_[TestSetup]_Should[ExpectedResult]

2. Please merge all the NextChar tests into one, using XUnit Data Driven Tests using the [Theroy] and [MemberData] attributes

See: http://stackoverflow.com/questions/22093843/pass-complex-parameters-to-theory 
Note: PropertyData was replaced with MemberData in the newer XUnit versions, but the example is still applicable

For more detailed info, see: http://ikeptwalking.com/writing-data-driven-tests-using-xunit/

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextCharTests.cs
> +        public void NextChar_ShouldReturnChar()
Missing test cases:
What happens if the random is null?
What happens if the NextChar(this Random random, CharType mode) is called with an invalid CharType?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDateTime.cs
> +    public class NextDateTime
Missing test cases: 
- What happens if the random is null?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDateTime.cs
> +            Assert.IsType<DateTime>(result);
Again - can you think of a scenario where the NextDateTime() method will return anything else?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDateTime.cs
> +            var result = random.NextDateTime(mivValue, maxValue);
Try running this generation a few hundred times to be sure that the randoms generated are always between the limits.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDoubleTests.cs
> +            Assert.IsType<double>(result);
As previews methods.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDoubleTests.cs
> +        public void NextDouble_ShouldReturnDouble()
Missing test cases:
- What happens if Random is null?
- NextDouble(this Random random, double minValue, double maxValue) - what happens if minValue is greater than maxValue?
- What happens if the minValue or maxValue are Infinity? And NaN?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +    public class NextStringTests
Missing test cases:
- What happens if Random is null?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +            for (int i = 0; i < OneHundred; i++)
You can do the whole string string Assert in one go:
`                var check = result.Select(x => x.IsLetter()).All(x => x);
                Assert.True(check);`

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +                Assert.True((currentChar >= 48 && currentChar < 58) || (currentChar >= 97 && currentChar < 123));
Magic numbers - please extract the check into a meaningful method. Or even write a new extension method?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +                Assert.True((currentChar >= 48 && currentChar < 58) || (currentChar >= 65 && currentChar < 91));
Magic numbers - please extract the check into a meaningful method.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +                Assert.True(result[i] >= 0 && result[i] < 65536);
Magic numbers - please extract the check into a meaningful method.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextTimeSpanTests.cs
> +            Assert.IsType<TimeSpan>(result);
Same as above.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextTimeSpanTests.cs
> +        public void NextTimeSpan_ShouldReturnTimeSpan()
Missing test cases:
- What happens if the Random is null?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/OneOfTests.cs
> +        public void OneOf_ShouldReturnOneOfIntCollection()
Testing for different types of collections is unnecessary. We are testing our method not the implementations of Arrays, List, etc.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/OneOfTests.cs
> +    public class OneOfTests
Missing test cases:
- What happens if the Random is null?
- What happens if the input list is null?

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet/Extensions/Common/RandomExtensions.cs
> +            var nextBool = random.NextDouble() <= probability;
No need to allocate a new variable, when we don't use it anywhere.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet/Extensions/Common/RandomExtensions.cs
> +            var aphabeticChar = random.NextAlphabeticChar(random.NextBool());
No need to allocate a new variable, when we don't use it anywhere.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet/Extensions/Common/RandomExtensions.cs
> +                var number = random.NextNumericChar();
No need to allocate a new variable, when we don't use it anywhere.

2016-10-27 10:43 UTC, Teodor92 commented on Source/MoreDotNet/Extensions/Common/RandomExtensions.cs
> +            char alphabeticChar;
No need to allocate a new variables, when we don't use them anywhere.

2016-10-29 19:20 UTC, vladislav-karamfilov requested changes

2016-10-29 19:20 UTC, vladislav-karamfilov commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDoubleTests.cs
> +            Assert.Throws<NullReferenceException>(() => random.NextDouble());
Should be `ArgumentNullException`.

2016-10-30 18:36 UTC, Teodor92 requested changes

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextBoolTests.cs
> +        private const int Counter = 10;
Please use more meaningful names for consts.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDateTime.cs
> +        private const int Counter = 1000;
Please use more meaningful names for consts.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDoubleTests.cs
> +        private const int Counter = 1000;
Please use more meaningful names for consts.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextBoolTests.cs
> +            Assert.Throws<NullReferenceException>(() => random.Next());
It should be `random.NextBool()`

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDateTime.cs
> +        private DateTime maxDate = new DateTime(2019, 10, 31);
Make the fields read only.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDoubleTests.cs
> +            Assert.Throws<NullReferenceException>(() => random.NextDouble());
You are testing the system implementation of NextDouble, no the actual overload extension method.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDoubleTests.cs
> +            Assert.Throws<ArgumentException>(() => random.NextDouble(minValue: MaxValue, maxValue: MinValue));
No need for name identifiers.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextDateTime.cs
> +            Random random = new Random();
Use `var` where possible.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +        private const int Zero = 0;
Unused const.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +            var check = result.Select(x => x.GetType() == typeof(char)).All(x => x);
No need to validate if a string consist of chars - that's in the language specification.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +            Assert.Throws<OutOfMemoryException>(() => random.NextString(int.MaxValue, MoreDotNet.Models.CharType.AnyUnicode));
Why should it throw and OutOfMemoryException?

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +            var check = result.Select(x => this.IsAlphanumericUpperChar(x)).All(x => x);
Use method group.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextStringTests.cs
> +            var check = result.Select(x => this.IsAlphanumericLowerChar(x)).All(x => x);
Use method group.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextTimeSpanTests.cs
> +        private TimeSpan maxTimeSpan = new TimeSpan(1000, 59, 59, 59);
Make fields read only.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/NextTimeSpanTests.cs
> +        private const int Counter = 1000;
Please use meaningful names for consts.

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/OneOfTests.cs
> +        private int[] numbersArr = new[] { 1, 2, 3, 4, 5, 6 };
- Do not use shorthands.
- Use meaningful names.
- you can do: `private int[] numbersArr = { 1, 2, 3, 4, 5, 6 };`

2016-10-30 18:36 UTC, Teodor92 commented on Source/MoreDotNet.Test/Extensions/Common/RandomExtensions/OneOfTests.cs
> +    using System.Collections.Generic;
Unused using.

2016-10-30 19:47 UTC, Teodor92 approved these changes

2016-10-30 19:50 UTC, vladislav-karamfilov approved these changes

2016-10-30 19:51 UTC, merged