Add tests for ByteArrayExtensions
Teodor92/MoreDotNet pull request #38
Opened 2016-10-30 18:34 UTC by M-Zuber

Fixed up some bugs found while testing.
Added UTF32 Big Endian
Closes #4

2016-10-31 20:57 UTC, vladislav-karamfilov reviewed
[Using the file system for unit tests is not cool](http://www.artima.com/weblogs/viewpost.jsp?thread=126923). In your case a better approach would be to use `Encoding.<SomeEncoding>.GetBytes()` method for getting the bytes of a string.

2016-10-31 21:25 UTC, M-Zuber commented
Arguable, but you have a point. 
Will verify in the morning that `...GetBytes()` returns the proper encoding markers also, to make sure it is testing a as close to real life situation as possible. 
If so will gladly update the PR. 

While I have your attention, any thoughts on how to identify a UTF16 file with zero in first two bytes after marking as opposed to thinking it is UTF32?

2016-11-02 07:34 UTC, M-Zuber commented
@Teodor92 fixed the issue with using the FS in the tests.

2016-11-06 18:36 UTC, vladislav-karamfilov commented
@M-Zuber, I can't think of a better approach than the additional check `bytes.Length % 4 == 0` added to the check for UTF-32. UTF-32 encoding is 4 bytes fixed-width and UTF-16 is variable 2 or 4 bytes so the check won't catch all cases correct but the change of getting the correct encoding is higher.

PS I'm sorry for my late answer. I was very busy last week...

2016-11-08 11:40 UTC, M-Zuber commented
@vladislav-karamfilov thanks for the tip, added a check + test for a UTF16 buffer with leading zeros.

So this should be finished and ready to merge

2016-11-08 11:44 UTC, vladislav-karamfilov requested changes

2016-11-08 11:44 UTC, vladislav-karamfilov commented on Source/MoreDotNet/Extensions/Common/ByteArrayExtensions.cs
> +            // In addition to preamble check the length to help UTF16 with leading zeros be recognized properly as UTF32 is 4 bytes fixed with and UTF 16 is 2
Small typos:
`fixed with` -> `fixed width`
`UTF16` -> `UTF-16`
`UTF 16` -> `UTF-16`
`UTF32` -> `UTF-32`

Also UTF-16 is has variable width of 2 or 4 bytes. It's good to update the comment. 😸

2016-11-08 11:45 UTC, vladislav-karamfilov commented
It looks good to me. Just a few improvements in a comment and I can merge it. :-)

2016-11-08 11:47 UTC, M-Zuber commented
Comments updated. Thanks.

2016-11-08 11:47 UTC, merged